### ISSUE TITLE
Option to stack potions

### ISSUE THREAD

**Issue by JZomerlei** [Dyldozer/SuppliesTrackerExternal#11]
It would be nice that prayer (1) * 16 would become prayer(4) * 4 because low dose is usually not exactly 1/4 the cost of a full four dose. 

Good work :)

**Comment by Dyldozer** [comment]
The price calc uses the price of a 4 dose / 4 to combat this already since most people use 4 dose

**Comment by JZomerlei** [comment]
Oh. Lol.
