### ISSUE TITLE
Maybe add Death toll

### ISSUE THREAD

**Issue by satyrsaw** [Dyldozer/SuppliesTrackerExternal#12]
Well i dont know the right term. But what i'm referring to is the tax when dieing at vorkath and having to pay the 100k. Make it so the 100k is added as a supply.

**Comment by Dyldozer** [comment]
I did work on a version of this before and it was buggy but I think I have a better way to do it, I'll try to add it thanks for the suggestion!

**Comment by Dyldozer** [comment]
added with latest commit
