### ISSUE TITLE
Cannonballs not being tracked

### ISSUE THREAD

**Issue by dereklance** [Dyldozer/SuppliesTrackerExternal#18]
Cannonballs used are not tracked

**Comment by Dyldozer** [comment]
I tested on 3 different client today and all of them tracked using both regular and granite cannonballs. Any specific instances or circumstances you noticed this?

**Comment by Dyldozer** [comment]
Didn't mean to close

**Comment by dereklance** [comment]
I noticed it when doing a slayer task with a blowpipe equipped. In the settings I also had adamant darts selected. Cannonballs were not added to the supply tracker as the cannon fired or after I reloaded the cannon. Still didn't work after unequipping blowpipe and just using cannon.
