### ISSUE TITLE
Toxic blowpipe ammo bug

### ISSUE THREAD

**Issue by ry4ng** [Dyldozer/SuppliesTrackerExternal#23]
I've been using this plugin for a few days while camping Zulrah. I have noticed that it will track the blowpipe ammo (darts & scales) fine for a while and then stop tracking them all together. 

I have verified this by manually checking the ammo and darts used in game and comparing it to the count on the plugin. 

So far I have not detected a pattern as to when it stops tracking the blowpipe ammo but it has happened a few times now, I have tried restarting Runelite however this does not seem to fix it.

**Comment by ry4ng** [comment]
Could this bug potentially be caused by quickly switching between gear setups at Zulrah?

**Comment by ry4ng** [comment]
?

**Comment by kblicharski** [comment]
I have this same issue. Please look into this instead of closing without comment. No matter what I've tried I cannot get the plugin to track blowpipe charges again.

**Comment by kblicharski** [comment]
@ry4ng @Dyldozer After restarting my client and the plugin it appears to be working again.
