### ISSUE TITLE
"Void mage helmet is a food?"

### ISSUE THREAD

**Issue by Alurk** [Dyldozer/SuppliesTrackerExternal#24]
![113](https://user-images.githubusercontent.com/69126633/89134695-99725a00-d4ec-11ea-8e73-15bed1bbff16.PNG)

Interesting bug. Not sure if I can replicate. Figured worth sharing and reporting.

**Comment by Dyldozer** [comment]
Thanks for report, ya its a hard bug to fix with how the detection method works. Im trying to get it out though
