### ISSUE TITLE
Track Supplies used between sessions

### ISSUE THREAD

**Issue by Drake356** [Dyldozer/SuppliesTrackerExternal#25]
Would it be possible to track the supplies used between sessions? For example doing part of a slayer task before logging off for the night and closing the client, then continuing the next day. All my supplies used the previous night will be gone whereas the runelite loot tracker will still have my drops but I won't know my profit because my supplies used the night before are no longer tracked.

**Comment by Dyldozer** [comment]
Added in this update tonight.
