### ISSUE TITLE
dragon arrows and addy/rune darts for blowpipe?

### ISSUE THREAD

**Issue by Vikerules** [Dyldozer/SuppliesTrackerExternal#31]
possible to fix so it doesnt assume you use dragon darts in your bp if you use twisted bow and dragon arrows? that shit too expensive mane

**Comment by Dyldozer** [comment]
@Vikerules the config options is where you can find dart use options. Currently there isn't a way to detect which dart is loaded into the blowpipe so it needs to be set manually
