### ISSUE TITLE
Settings do not save after client restart

### ISSUE THREAD

**Issue by asherbasher** [Dyldozer/SuppliesTrackerExternal#5]
Every time I restart my client the darts reset to Mithril and the weapon charges box resets to unticked. I would expect the settings to save across restarts.

**Comment by Dyldozer** [comment]
I will look into it tonight thank you for the heads up

**Comment by asherbasher** [comment]
> I will look into it tonight thank you for the heads up

Had any chance to work on it? Really like this plugin but I always forget to change settings each day.

**Comment by asherbasher** [comment]
Narrowed the issue down further. It only seems to happen if you are logged in with a RuneLite/Google profile. For some reason it refuses to save to that, but if you don't log in to a RuneLite profile it saves fine.
